// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using SURA.Views.AppPublico.Soluciones;
//
//    var modeloJson = ModeloJson.FromJson(jsonString);

namespace SURA.Views.AppPublico.Soluciones
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ModeloJson
    {
        [JsonProperty("Seguro_Auto")]
        public List<Seguro> SeguroAuto { get; set; }

        [JsonProperty("Seguro_Vida")]
        public List<Seguro> SeguroVida { get; set; }

        [JsonProperty("Seguro_Asistencia_Funeraria")]
        public List<Seguro> SeguroAsistenciaFuneraria { get; set; }

        [JsonProperty("Seguro_PAM")]
        public List<SeguroPam> SeguroPam { get; set; }

        [JsonProperty("Seguro_Accidente")]
        public List<Seguro> SeguroAccidente { get; set; }

        [JsonProperty("Seguro_Hogar")]
        public List<Seguro> SeguroHogar { get; set; }

        [JsonProperty("Seguro_Negocio")]
        public List<Seguro> SeguroNegocio { get; set; }
    }

    public partial class Seguro
    {
        [JsonProperty("NombreSeguro")]
        public string NombreSeguro { get; set; }

        [JsonProperty("ProductIcon")]
        public string ProductIcon { get; set; }

        [JsonProperty("ProductBanner")]
        public string ProductBanner { get; set; }

        [JsonProperty("Slogan_1")]
        public string Slogan1 { get; set; }

        [JsonProperty("Slogan_2")]
        public string Slogan2 { get; set; }

        [JsonProperty("TipoPlan")]
        public string TipoPlan { get; set; }

        [JsonProperty("Ventajas")]
        public List<PorqueYoElement> Ventajas { get; set; }

        [JsonProperty("Cobertura")]
        public List<PorqueYoElement> Cobertura { get; set; }

        [JsonProperty("DanosTerceros")]
        public List<PorqueYoElement> DanosTerceros { get; set; }

        [JsonProperty("PorqueYo")]
        public List<PorqueYoElement> PorqueYo { get; set; }

        [JsonProperty("Planes")]
        public List<PorqueYoElement> Planes { get; set; }
    }

    public partial class Cobertura
    {
        [JsonProperty("Titulo")]
        public string Titulo { get; set; }

        [JsonProperty("Descripcion")]
        public string Descripcion { get; set; }

        [JsonProperty("Lista")]
        public List<string> Lista { get; set; }

        [JsonProperty("DanosTerceros")]
        public object DanosTerceros { get; set; }

        [JsonProperty("Planes")]
        public object Planes { get; set; }
    }

    public partial class PorqueYoElement
    {
        [JsonProperty("Titulo")]
        public string Titulo { get; set; }

        [JsonProperty("Descripcion")]
        public string Descripcion { get; set; }
        
        [JsonProperty("Disclaimer")]
        public string Disclaimer { get; set; }

        [JsonProperty("Lista")]
        public List<string> Lista { get; set; }
    }

    public partial class SeguroPam
    {
        [JsonProperty("NombreSeguro")]
        public string NombreSeguro { get; set; }

        [JsonProperty("ProductIcon")]
        public string ProductIcon { get; set; }

        [JsonProperty("ProductBanner")]
        public string ProductBanner { get; set; }

        [JsonProperty("Slogan_1")]
        public string Slogan1 { get; set; }

        [JsonProperty("Slogan_2")]
        public string Slogan2 { get; set; }

        [JsonProperty("TipoPlan")]
        public string TipoPlan { get; set; }

        [JsonProperty("Ventajas")]
        public List<PorqueYoElement> Ventajas { get; set; }

        [JsonProperty("Cobertura")]
        public List<PorqueYoElement> Cobertura { get; set; }

        [JsonProperty("PorqueYo")]
        public List<PorqueYoElement> PorqueYo { get; set; }

        [JsonProperty("DanosTerceros")]
        public object DanosTerceros { get; set; }

        [JsonProperty("Planes")]
        public object Planes { get; set; }
    }

    public partial class ModeloJson
    {
        public static ModeloJson FromJson(string json) => JsonConvert.DeserializeObject<ModeloJson>(json, SURA.Views.AppPublico.Soluciones.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ModeloJson self) => JsonConvert.SerializeObject(self, SURA.Views.AppPublico.Soluciones.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
