// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using SURA.Models;
//
//    var modeloResultadoDetalle = ModeloResultadoDetalle.FromJson(jsonString);

namespace SURA.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using System.IO;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using SURA.Services;
    using Xamarin.Forms;

    public partial class ModeloResultadoDetalle
    {
        public string PlaceId { get; set; }

        public string FormattedAddress { get; set; }

        public string FormattedPhoneNumber { get; set; }

        public string Name { get; set; }

        public List<string> WeekdayText { get; set; }

        public Byte[] Photos { get; set; }

        public PhotoAttribution photoAttribution {get;set;}

        public class PhotoAttribution
        {
            public string PhotoUrl { get; set; }
            public string PhotoName { get; set; }
        }
    }


    public partial class ModeloResultadoDetalle
    {
        public static ModeloResultadoDetalle FromJson(string json) => JsonConvert.DeserializeObject<ModeloResultadoDetalle>(json, SURA.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ModeloResultadoDetalle self) => JsonConvert.SerializeObject(self, SURA.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
